spring:
  datasource:
    url: jdbc:mysql:///jpa?serverTimezone=UTC
    password: 25002500
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      更新或者创建数据表
      ddl-auto: update
#      控制台打印sql语句
    show-sql: true